# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 04:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselift',
            name='exercise_priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exerciselift',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='exerciselift',
            name='video',
            field=models.FileField(upload_to='lifts/'),
        ),
        migrations.AlterField(
            model_name='exercisetype',
            name='rep_range_per_set',
            field=models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
