# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='workouttracker',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
