# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160922_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisetype',
            name='type_priority',
            field=models.IntegerField(default=0),
        ),
    ]
